version: '3'
services:
  db:
    image: mysql:8.0
    environment:
    - MYSQL_ROOT_PASSWORD=redacted
    - MYSQL_DATABASE=redacted
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    restart: always
    ports:
    - "9007:3000"
    depends_on:
      db:
        condition: service_healthy
